### ISSUE TITLE
Display problem in "00 - Prerequisites.pdf"

### ISSUE THREAD

**Issue by Flood1993** [joaquinvanschoren/ML-course#3]
Some packages are cut off out of the PDF.

Example:
![image](https://user-images.githubusercontent.com/8102496/35863697-bdde5510-0b4f-11e8-8037-be7ad16ed16d.png)

**Comment by joaquinvanschoren** [comment]
Thanks, will look into it. Please check the notebook for now:
https://github.com/joaquinvanschoren/ML-course/blob/master/00%20-%20Prerequisites.ipynb

**Comment by joaquinvanschoren** [comment]
This is fixed with the new templates for exporting PDFs
