### ISSUE TITLE
openML has dependency on Visual Studio Build Tools

### ISSUE THREAD

**Issue by ikbenbeter** [joaquinvanschoren/ML-course#7]
When I was installing openML on windows, I had several issues. As it turns out, one of the packages included, netifaces, requires Visual C++ Build Tools to be installed. It would be helpful for future students with this issue if you include this information somewhere. Even if it is a very common program to have installed, I personally had recently emptied my hard disk so I did not have it installed. pip does not clearly state this package is required.

**Comment by joaquinvanschoren** [comment]
Thanks. I added a not about this on Canvas, but now also added it to the prerequisites file.
https://github.com/joaquinvanschoren/ML-course/commit/36c55f515511121cac0802a2904ba836a9a503e9
