### ISSUE TITLE
Missing data.csv in 00 - Tutorial 2a - Python for Data Analysis

### ISSUE THREAD

**Issue by schneiderjan** [joaquinvanschoren/ML-course#8]
>dfs = pd.read_csv('data.csv')
dfs
dfs.set_value(0, 'a', 10)
dfs.to_csv('data.csv', index=False) # Don't export the row index`

if this is run you get following error:

`OSError: File b'data.csv' does not exist`

I cannot find the data.csv anywhere in the repo either.

**Comment by joaquinvanschoren** [comment]
Thanks! I added this last week.

**Comment by joaquinvanschoren** [comment]
Sorry, I thought that this was about another file. 
You are right, I pushed an update:
https://github.com/joaquinvanschoren/ML-course/commit/fbb4a57c1e5bb47c997ba845f94ca7c208cac906
